export const skills = {
    heading: "Skills",
    quote: "Build your skills, not your resume",
    techSkills: [
        "JavaScript",
        "NodeJS",
        "ReactJS",
        "React Native",
        "Redux",
        "C++",
        "C#",
        "C",
        "Java",
        "Python",
        "HTML",
        "CSS",
        "jQuery",
        "Bootstrap",
        "Material Design",
        "MaterializeCSS",
        "Git",
        "GitHub",
        "MongoDB",
    ],
    industryKnowledge: [
        "Software Project Management",
        "Marketing",
        "Publicity",
        "Blogging",
        "Content Writing",
        "Creative Writing",
        "Web Content Writing",
        "Frontend Development",
        "Software Development",
        "Backend Development",
        "Design",
        "Web Development",
        "Android App Development"
    ],
    interpersonalSkills: [
        "Communication",
        "Teaching",
        "Time Management",
        "Leadership",
        "Management"
    ]
};